version: '3.1' # specify docker-compose version

services:
  postgresdb:
    image: postgres:latest
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: always
    container_name: "postgresdb-jdbc-database"
    environment:
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: postgres
      POSTGRES_USER: quarkus
    volumes:
      - ./import.sql:/docker-entrypoint-initdb.d/init.sql

  taxation-service:
    image: schallabajzr/quarkus-taxation-service
    container_name: "taxation-example"
    build:
      context: ./
      dockerfile: ./src/main/docker/Dockerfile.multipart
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgresdb:5432/postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb