# datasource configuration
"%prod":
  quarkus:
    swagger-ui:
      always-include: true
    datasource:
      db-kind: postgresql
      username: quarkus
      password: quarkus
      jdbc:
        url: jdbc:postgresql://localhost:5432/quarkus
"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      username: quarkus
      password: quarkus
      jdbc:
        url: jdbc:postgresql://localhost:5432/quarkus
    hibernate-orm:
      database:
        generation: drop-and-create
    log:
      sql: true
    sql-load-script: import.sql
"%test":
  quarkus:
    hibernate-orm:
      database:
        generation: drop-and-create
    log:
      sql: true
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:tcp://localhost/mem:default